language: python
python:
  - "2.6"
  - "2.7"
env:
  - MC_TEST_USE_SOUTH= MC_TEST_USE_ES= MC_TEST_MYSQL=
  - MC_TEST_USE_SOUTH=yes
  - MC_TEST_USE_ES=yes
  - MC_TEST_MYSQL=yes
before_install:
  - test x$MC_TEST_USE_ES == xyes && sudo service elasticsearch start && sleep 3 || true
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - "export DISPLAY=:99.0" 
  
install:
  - pip install -q -e . --use-mirrors
  - pip install -q --use-mirrors -r example_mc_project/requirements.txt
  - pip install selenium
  - test x$MC_TEST_USE_SOUTH == xyes && pip install -q --use-mirrors south || true
  - test x$MC_TEST_USE_ES == xyes && pip install -q 'git+git://github.com/toastdriven/pyelasticsearch.git' || true
  - test x$MC_TEST_MYSQL == xyes && pip install -q --use-mirrors mysql-python || true
before_script:
  - mysql -e 'CREATE DATABASE miro_community_example CHARACTER SET utf8 COLLATE utf8_bin;'
script:
  - django-admin.py test localtv --settings=example_mc_project.settings --verbosity=2
  - django-admin.py test contests --settings=example_mc_project.settings --verbosity=2
